
package forms;
import java.sql.Connection;
import Clases.Cuenta;
import Clases.CuentaDAO;
import Clases.LibroMayor;
import Clases.LibroMayorDAO;
import clases.Conexion;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author luisc
 */
public class PanelLibroMayor extends javax.swing.JPanel {

    /**
     * Creates new form PanelPartidas
     */
    public PanelLibroMayor() {
        initComponents();
        this.cargarCuentas();
        this.configurarTabla();
        this.estiloTabla(); 
 
    }

    
    DefaultTableModel modelo = new DefaultTableModel();
    
    private void configurarTabla() {

    modelo = new DefaultTableModel();

    modelo.addColumn("Fecha");
    modelo.addColumn("Asiento");
    modelo.addColumn("Concepto");
    modelo.addColumn("Debe");
    modelo.addColumn("Haber");
    modelo.addColumn("Saldo");

    tblMayor.setModel(modelo);

    tblMayor.setRowHeight(30);

    tblMayor.getTableHeader().setFont(
        new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 13)
    );
}
    
    private void llenarTabla(List<LibroMayor> lista) {
    modelo.setRowCount(0);
    for (LibroMayor lm : lista) {
        modelo.addRow(new Object[]{
            lm.getFecha(),
            lm.getNumeroAsiento(),
            lm.getConcepto(),
            lm.getDebe(),
            lm.getHaber(),
            lm.getSaldo()
        });
    }
}
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTitulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        panelContenido = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cmbCuenta = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ftxtFechaInicio = new javax.swing.JFormattedTextField();
        ftxtFechaFin = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMayor = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));
        setPreferredSize(new java.awt.Dimension(1270, 100));
        setRequestFocusEnabled(false);
        setLayout(new java.awt.BorderLayout());

        panelTitulo.setBackground(new java.awt.Color(255, 255, 255));
        panelTitulo.setPreferredSize(new java.awt.Dimension(1270, 80));
        panelTitulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Libro Mayor");
        panelTitulo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 340, 35));

        jPanel1.setBackground(new java.awt.Color(59, 116, 231));
        jPanel1.setPreferredSize(new java.awt.Dimension(270, 5));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelTitulo.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 360, 5));

        add(panelTitulo, java.awt.BorderLayout.NORTH);

        panelContenido.setBackground(new java.awt.Color(255, 255, 255));
        panelContenido.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Cuenta:");
        panelContenido.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, -1, -1));

        cmbCuenta.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        cmbCuenta.setPreferredSize(new java.awt.Dimension(250, 28));
        cmbCuenta.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbCuentaItemStateChanged(evt);
            }
        });
        cmbCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbCuentaMouseClicked(evt);
            }
        });
        cmbCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCuentaActionPerformed(evt);
            }
        });
        panelContenido.add(cmbCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 290, 24));

        jButton1.setBackground(new java.awt.Color(0, 102, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panelContenido.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, 90, 30));

        jLabel3.setText("Fecha Fin:");
        panelContenido.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, -1, -1));

        jLabel4.setText("Fecha Inicio:");
        panelContenido.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, -1, -1));

        try {
            ftxtFechaInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftxtFechaInicio.setPreferredSize(new java.awt.Dimension(120, 28));
        ftxtFechaInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftxtFechaInicioActionPerformed(evt);
            }
        });
        panelContenido.add(ftxtFechaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 90, 30));

        try {
            ftxtFechaFin.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftxtFechaFin.setPreferredSize(new java.awt.Dimension(120, 28));
        ftxtFechaFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftxtFechaFinActionPerformed(evt);
            }
        });
        panelContenido.add(ftxtFechaFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 90, 30));

        tblMayor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblMayor);

        panelContenido.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 880, 380));

        jButton2.setBackground(new java.awt.Color(0, 0, 153));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Limpiar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        panelContenido.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 30, 90, 30));

        add(panelContenido, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    
    
     private void cargarCuentas() {
        CuentaDAO dao = new CuentaDAO();
        cmbCuenta.removeAllItems();
        for (Cuenta c : dao.listarCuentasParaCMB()) {
            ((JComboBox) cmbCuenta).addItem(c);
        }
    }
    private void cmbCuentaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbCuentaItemStateChanged
        // TODO add your handling code here:
        //    this.traersubCuentas();
    }//GEN-LAST:event_cmbCuentaItemStateChanged

    private void cmbCuentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbCuentaMouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCuentaMouseClicked

    private void cmbCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCuentaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      Connection con = null;
    try {
        con = Conexion.conectar();
        LibroMayorDAO dao = new LibroMayorDAO();
        Cuenta cuenta = (Cuenta) cmbCuenta.getSelectedItem();
        if (cuenta == null) {
            JOptionPane.showMessageDialog(this,
                    "Seleccione una cuenta");
            return;
        }
        // convertir texto dd/MM/yyyy a Date
        java.text.SimpleDateFormat sdf =
                new java.text.SimpleDateFormat("dd/MM/yyyy");

        java.util.Date inicio =
                sdf.parse(ftxtFechaInicio.getText());
        java.util.Date fin =
                sdf.parse(ftxtFechaFin.getText());
        java.sql.Date fechaInicio =
                new java.sql.Date(inicio.getTime());
        java.sql.Date fechaFin =
                new java.sql.Date(fin.getTime());
        List<LibroMayor> lista =dao.listarLibroMayor(cuenta.getId(),fechaInicio,fechaFin,con);

        llenarTabla(lista);

    } catch (Exception e) {

        JOptionPane.showMessageDialog(this,
                "Error: " + e.getMessage());
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ftxtFechaFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftxtFechaFinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftxtFechaFinActionPerformed

    private void ftxtFechaInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftxtFechaInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftxtFechaInicioActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        modelo.setRowCount(0);
        ftxtFechaInicio.setText("");
        ftxtFechaFin.setText("");

    }//GEN-LAST:event_jButton2ActionPerformed

    
    // mejora de interfaz
    private void estiloTabla() {

        tblMayor.setDefaultRenderer(Object.class,
                new javax.swing.table.DefaultTableCellRenderer() {

            @Override
            public java.awt.Component getTableCellRendererComponent(
                    javax.swing.JTable table,
                    Object value,
                    boolean isSelected,
                    boolean hasFocus,
                    int row,
                    int column) {

                java.awt.Component c
                        = super.getTableCellRendererComponent(
                                table, value, isSelected, hasFocus, row, column);

                if (!isSelected) {
                    if (row % 2 == 0) {
                        c.setBackground(new java.awt.Color(232, 242, 252));
                    } else {
                        c.setBackground(java.awt.Color.WHITE);
                    }
                }

                return c;
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbCuenta;
    private javax.swing.JFormattedTextField ftxtFechaFin;
    private javax.swing.JFormattedTextField ftxtFechaInicio;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelContenido;
    private javax.swing.JPanel panelTitulo;
    private javax.swing.JTable tblMayor;
    // End of variables declaration//GEN-END:variables
}
